# Generated by Django 3.2.9 on 2022-04-12 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_tank', models.IntegerField()),
                ('consumption', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAirplanes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airplane', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airplane_of_company', to='main.airplane')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_airplane', to='main.company')),
            ],
        ),
    ]
